# Generated by Django 4.1.7 on 2023-02-18 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('languageid', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('jobid', models.IntegerField()),
            ],
        ),
    ]
