# Generated by Django 4.1.7 on 2023-02-25 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_remove_job_jobid'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='link',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
